// Shared helpers for the D1-backed course builder (modules + steps).
// Used by both the admin builder API and the public step player.

export interface CourseStepRow {
  id: string;
  module_id: string;
  title: string;
  content_type: 'text' | 'video';
  content_body: string | null;
  video_url: string | null;
  sequence_order: number;
  question: string | null;
  question_options: string | null; // JSON string
  question_correct_index: number | null;
}

export interface CourseModuleRow {
  id: string;
  course_slug: string;
  title: string;
  sequence_order: number;
}

export interface ModuleWithSteps extends CourseModuleRow {
  steps: CourseStepRow[];
}

export async function getCourseOutline(db: any, courseSlug: string): Promise<ModuleWithSteps[]> {
  const modules = (
    await db
      .prepare(`SELECT * FROM course_modules WHERE course_slug = ? ORDER BY sequence_order, created_at`)
      .bind(courseSlug)
      .all()
  ).results as CourseModuleRow[];

  const steps = (
    await db
      .prepare(
        `SELECT s.* FROM course_steps s
         JOIN course_modules m ON s.module_id = m.id
         WHERE m.course_slug = ?
         ORDER BY s.sequence_order, s.created_at`
      )
      .bind(courseSlug)
      .all()
  ).results as CourseStepRow[];

  return modules.map((m) => ({ ...m, steps: steps.filter((s) => s.module_id === m.id) }));
}

export async function getCompletedStepIds(db: any, courseSlug: string, email: string): Promise<Set<string>> {
  const rows = (
    await db
      .prepare(`SELECT step_id FROM step_completions WHERE course_slug = ? AND email = ?`)
      .bind(courseSlug, email.trim().toLowerCase())
      .all()
  ).results as { step_id: string }[];
  return new Set(rows.map((r) => r.step_id));
}

// Tags lesson content is allowed to use when it already contains real HTML
// (e.g. content generated by the automation pipeline). Anything else gets
// stripped, attributes included, so a compromised/careless content source
// can't inject scripts, styles, or event handlers into the page.
const ALLOWED_TAGS = new Set([
  'p', 'h3', 'h4', 'em', 'strong', 'b', 'i', 'ul', 'ol', 'li', 'br', 'blockquote',
]);

// True if the text already looks like it contains real HTML block/inline
// tags (as opposed to plain text that just happens to contain a literal
// "<" character).
function looksLikeHtml(text: string): boolean {
  return /<\s*(p|h[1-6]|ul|ol|li|em|strong|b|i|br|blockquote)(\s|>|\/)/i.test(text);
}

// Strips <script>/<style> blocks entirely (tag + contents), then strips
// every tag not on the allow-list (keeping its inner text) and strips all
// attributes from tags that are kept -- so even trusted content can't
// smuggle in onclick handlers, style overrides, etc.
function sanitizeHtml(html: string): string {
  let out = html.replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/gi, '');
  out = out.replace(/<\/?([a-zA-Z0-9]+)[^>]*>/g, (match, tag) => {
    const lower = String(tag).toLowerCase();
    if (!ALLOWED_TAGS.has(lower)) return '';
    return match.startsWith('</') ? `</${lower}>` : `<${lower}>`;
  });
  return out;
}

// Renders lesson content stored in content_body. Handles two cases:
// 1. Plain text typed into the dashboard's lesson textarea (no HTML tags) --
//    escaped, then blank-line-separated blocks become paragraphs and single
//    newlines become <br>. This is the original dependency-free behavior.
// 2. Content that already contains real HTML (e.g. from the course
//    automation pipeline) -- passed through a small allow-list sanitizer
//    instead of being escaped, so it renders as actual formatted HTML.
export function textToHtml(text: string): string {
  if (looksLikeHtml(text)) {
    return sanitizeHtml(text);
  }
  const escape = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return text
    .split(/\n{2,}/)
    .map((block) => `<p>${escape(block.trim()).replace(/\n/g, '<br>')}</p>`)
    .join('\n');
}
